--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

-- Started on 2022-11-22 17:13:36

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3355 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 25542)
-- Name: balance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.balance (
    id bigint NOT NULL,
    balance bigint NOT NULL,
    customer_id bigint NOT NULL
);


ALTER TABLE public.balance OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 25541)
-- Name: balance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.balance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.balance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 25534)
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    created_timestamp timestamp with time zone NOT NULL,
    disabled_timestamp timestamp with time zone
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 25533)
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 25528)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 25523)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 25553)
-- Name: operation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operation (
    id bigint NOT NULL,
    operation_code character varying(255) NOT NULL,
    operation_timestamp timestamp with time zone NOT NULL,
    amount bigint NOT NULL,
    customer_id bigint NOT NULL
);


ALTER TABLE public.operation OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 25552)
-- Name: operation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.operation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 25565)
-- Name: transfer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transfer (
    id bigint NOT NULL,
    recipient_operation_id bigint NOT NULL,
    sender_operation_id bigint NOT NULL
);


ALTER TABLE public.transfer OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25564)
-- Name: transfer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transfer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transfer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3345 (class 0 OID 25542)
-- Dependencies: 214
-- Data for Name: balance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.balance (id, balance, customer_id) FROM stdin;
3	0	3
1	90	1
2	180	2
\.


--
-- TOC entry 3343 (class 0 OID 25534)
-- Dependencies: 212
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer (id, firstname, lastname, created_timestamp, disabled_timestamp) FROM stdin;
1	Sergey	Kovalev	2022-11-20 17:55:02.427208+03	\N
2	Иван	Петров	2022-11-20 17:55:46.756073+03	\N
3	Федор	Смирнов	2022-11-20 17:56:28.116139+03	2022-11-20 17:58:36.805566+03
\.


--
-- TOC entry 3341 (class 0 OID 25528)
-- Dependencies: 210
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
01_create_table_customer	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:52:51.851015	1	EXECUTED	8:8434e1a1b04b4ef300118edb8bec4263	sql		\N	4.9.1	\N	\N	8955971751
02_create_table_balance	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:52:51.87668	2	EXECUTED	8:8d879e945aa3f133f72c804148ae0370	sql		\N	4.9.1	\N	\N	8955971751
03_create_fk_balance_on_customer	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:52:51.936414	3	EXECUTED	8:da784830c10dd265f813e61298e52369	sql		\N	4.9.1	\N	\N	8955971751
04_create_table_operation	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:52:51.963304	4	EXECUTED	8:0d9d2a591c813df4601553ccf7e06b2b	sql		\N	4.9.1	\N	\N	8955971751
05_create_fk_operations_on_customer	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:53:36.808911	5	EXECUTED	8:07ea876e4e51640de74ef8039fd3f128	sql		\N	4.9.1	\N	\N	8956016703
06_create_table_transfer	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:53:36.835474	6	EXECUTED	8:db2c5c0c31848ab7279d06d2bb58afde	sql		\N	4.9.1	\N	\N	8956016703
07_create_fk_transfer_on_recipient_operation	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:53:36.956449	7	EXECUTED	8:f17aabc26a9fab9b097e9dff3e101e1a	sql		\N	4.9.1	\N	\N	8956016703
08_create_fk_transfer_on_sender_operation	dipdeepcode	db/changelog/changeset/01_init_create_tables.yaml	2022-11-20 17:53:37.014545	8	EXECUTED	8:48173de3a9cbc45a790805b1e8e5d6da	sql		\N	4.9.1	\N	\N	8956016703
\.


--
-- TOC entry 3340 (class 0 OID 25523)
-- Dependencies: 209
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- TOC entry 3347 (class 0 OID 25553)
-- Dependencies: 216
-- Data for Name: operation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operation (id, operation_code, operation_timestamp, amount, customer_id) FROM stdin;
1	PUT_MONEY	2022-11-20 17:59:24.830469+03	100	1
2	PUT_MONEY	2022-11-20 17:59:47.824222+03	200	2
3	TAKE_MONEY	2022-11-20 18:00:05.205343+03	10	1
4	TAKE_MONEY	2022-11-20 18:00:12.573797+03	20	2
\.


--
-- TOC entry 3349 (class 0 OID 25565)
-- Dependencies: 218
-- Data for Name: transfer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transfer (id, recipient_operation_id, sender_operation_id) FROM stdin;
\.


--
-- TOC entry 3356 (class 0 OID 0)
-- Dependencies: 213
-- Name: balance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.balance_id_seq', 3, true);


--
-- TOC entry 3357 (class 0 OID 0)
-- Dependencies: 211
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customer_id_seq', 3, true);


--
-- TOC entry 3358 (class 0 OID 0)
-- Dependencies: 215
-- Name: operation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operation_id_seq', 4, true);


--
-- TOC entry 3359 (class 0 OID 0)
-- Dependencies: 217
-- Name: transfer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transfer_id_seq', 1, false);


--
-- TOC entry 3188 (class 2606 OID 25527)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 3192 (class 2606 OID 25546)
-- Name: balance pk_balance; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT pk_balance PRIMARY KEY (id);


--
-- TOC entry 3190 (class 2606 OID 25540)
-- Name: customer pk_customer; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT pk_customer PRIMARY KEY (id);


--
-- TOC entry 3194 (class 2606 OID 25557)
-- Name: operation pk_operations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT pk_operations PRIMARY KEY (id);


--
-- TOC entry 3196 (class 2606 OID 25569)
-- Name: transfer pk_transfer; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfer
    ADD CONSTRAINT pk_transfer PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 25547)
-- Name: balance fk_balance_on_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT fk_balance_on_customer FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- TOC entry 3198 (class 2606 OID 25559)
-- Name: operation fk_operations_on_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT fk_operations_on_customer FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- TOC entry 3199 (class 2606 OID 25570)
-- Name: transfer fk_transfer_on_recipient_operation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfer
    ADD CONSTRAINT fk_transfer_on_recipient_operation FOREIGN KEY (recipient_operation_id) REFERENCES public.operation(id);


--
-- TOC entry 3200 (class 2606 OID 25575)
-- Name: transfer fk_transfer_on_sender_operation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfer
    ADD CONSTRAINT fk_transfer_on_sender_operation FOREIGN KEY (sender_operation_id) REFERENCES public.operation(id);


-- Completed on 2022-11-22 17:13:36

--
-- PostgreSQL database dump complete
--

